import '../assets/well.png'

export default{
    "success":true,
    "data":{
        "memes":[


            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/well.png',
                "width":1200,
                "boxcount":2
            },
            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/dog.png',
                "width":1200,
                "boxcount":2
            },
            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/captain.png',
                "width":1200,
                "boxcount":2
            },

            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/well.png',
                "width":1200,
                "boxcount":2
            },
            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/dog.png',
                "width":1200,
                "boxcount":2
            },
            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/captain.png',
                "width":1200,
                "boxcount":2
            },

            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/well.png',
                "width":1200,
                "boxcount":2
            },
            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/dog.png',
                "width":1200,
                "boxcount":2
            },
            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/captain.png',
                "width":1200,
                "boxcount":2
            },

            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/well.png',
                "width":1200,
                "boxcount":2
            },
            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/dog.png',
                "width":1200,
                "boxcount":2
            },
            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/captain.png',
                "width":1200,
                "boxcount":2
            },

            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/well.png',
                "width":1200,
                "boxcount":2
            },
            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/dog.png',
                "width":1200,
                "boxcount":2
            },
            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/captain.png',
                "width":1200,
                "boxcount":2
            },

            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/well.png',
                "width":1200,
                "boxcount":2
            },
            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/dog.png',
                "width":1200,
                "boxcount":2
            },
            {
                "id":"11",
                "name":"drake",
                "url":'../src/assets/captain.png',
                "width":1200,
                "boxcount":2
            },
          
      
        ]
    }
}